### ISSUE TITLE
[BUG] 下载咪咕源 FLAC 音乐时出错

### ISSUE THREAD

**Issue by Lurito** [CharlesPikachu/musicdl#23]
**Environment (使用环境)**

- Installation method (安装方式): pip
- The version of musicdl (版本号): 2.3.5
- Operating system (操作系统): Windows 10
- Python version (Python版本): 3.10.5

**Question description (问题描述)**

下载咪咕源的 FLAC 格式音乐时会出错，mp3 格式不会出现问题。由于没找到其他平台的 FLAC 音乐所以其他平台无法测试。

**Screenshot (报错截图)**

```
Welcome to use musicdl!
You can visit https://github.com/CharlesPikachu/musicdl for more details.
2022-09-13 17:47:24 INFO     正在搜索 稻香 来自 MIGU
+------+--------+----------------------------------+---------+-------+----------------------------------+------+
| 序号 |  歌手  |               歌名               |   大小  |  时长 |               专辑               | 来源 |
+------+--------+----------------------------------+---------+-------+----------------------------------+------+
|  0   | 周杰伦 |               稻香               | 24.92MB | -:-:- |              魔杰座              | MIGU |
|  1   | 周杰伦 | 稻香(央视星光璀璨中国巨星演唱会) |  8.32MB | -:-:- | 央视星光璀璨中国巨星演唱会第四期 | MIGU |
|  2   | 周杰伦 |           稻香 (Live)            |  22.4MB | -:-:- |   周杰伦地表最强世界巡回演唱会   | MIGU |
|  3   | 周杰伦 |           稻香 (Live)            | 23.55MB | -:-:- |    The Era 2010 超时代演唱会     | MIGU |
|  4   | 谢昊轩 |      稻香(中国新声代第三季)      | 17.71MB | -:-:- |                -                 | MIGU |
+------+--------+----------------------------------+---------+-------+----------------------------------+------+
请输入想要下载的音乐编号: 0
2022-09-13 17:47:29 INFO     正在从MIGU下载 >>>> 稻香
Traceback (most recent call last):
  File "C:\Python310\Scripts\musicdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('musicdl==2.3.5', 'console_scripts', 'musicdl')())
  File "C:\Python310\lib\site-packages\click-8.1.3-py3.10.egg\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click-8.1.3-py3.10.egg\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click-8.1.3-py3.10.egg\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click-8.1.3-py3.10.egg\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\musicdl-2.3.5-py3.10.egg\musicdl\musicdl.py", line 208, in musicdlcmd
  File "C:\Python310\lib\site-packages\musicdl-2.3.5-py3.10.egg\musicdl\musicdl.py", line 131, in download
  File "C:\Python310\lib\site-packages\musicdl-2.3.5-py3.10.egg\musicdl\modules\sources\base.py", line 29, in download
  File "C:\Python310\lib\site-packages\musicdl-2.3.5-py3.10.egg\musicdl\modules\utils\downloader.py", line 28, in start
  File "C:\Python310\lib\site-packages\requests-2.28.1-py3.10.egg\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

**Comment by CharlesPikachu** [comment]
我测试了一下，应该是因为这些歌曲没有在线听的功能了。

**Comment by CharlesPikachu** [comment]
已经恢复了咪咕的flac支持
